#!/bin/bash
total 20                                                                           

-rwxr--r-- 1 root root 16 Feb  8 12:23 0-current_working_directory                 

-rwxr--r-- 1 root root 15 Feb  8 12:27 1-listit                                    

-rwxr--r-- 1 root root 21 Feb  8 12:59 2-bring_me_home                             

-rwxr--r-- 1 root root 36 Feb  8 13:01 3-listfiles                                 

-rw-r--r-- 1 root root 17 Feb  8 12:24 README.md   
